from util.model import Model
from util.prompt_templates.code_prompt import CODE_PROMPT
from util.prompt_templates.explain_prompt import EXPLAIN_PROMPT
from util.prompt_templates.sys_code_prompt import SYS_CODE_PROMPT
from util.prompt_templates.sys_explain_prompt import SYS_EXPLAIN_PROMPT
from util.prompt_templates.sys_update_prompt import SYS_UPDATE_PROMPT